{% set name = "aioboto3" %}
{% set version = "15.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37763bbc6321ceb479106dc63bc84c8fdb59dd02540034a12941aebef2057c5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68.2.0
    - setuptools-scm >=8.0.0
  run:
    - python >={{ python_min }}
    - aiobotocore ==2.24.0
    - aiofiles >=23.2.1
    - boto3 >=1.21.21
    - cryptography >=44.0.1
    - idna >=3.3.0


test:
  requires:
    - python {{ python_min }}
  imports:
    - aioboto3
    - aioboto3.s3

about:
  home: https://github.com/terrycain/aioboto3
  summary: 'Wrapper to use boto3 resources with the aiobotocore async backend'
  description: |
    aiobotocore allows you to use near enough all of the boto3 client commands in an async manner just by prefixing the command with await.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://aioboto3.readthedocs.io/en/latest/
  dev_url: https://github.com/terrycain/aioboto3

extra:
  recipe-maintainers:
    - peterbygrave
    - dgasmith
    - skrsna
    - markllama
